CREATE DATABASE SisTasks;
USE SisTasks;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PESSOA_FISICA_JURIDICA INT NOT NULL, -- 0 para pessoa física, 1 para pessoa jurídica
    CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE, -- UNIQUE para garantir que não haja duplicidade de CNPJ
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE TASKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO VARCHAR(5000) NULL,
    DATA_CRIACAO DATETIME NULL,
    DATA_INICIO DATETIME NULL,
    DATA_PAUSA DATETIME NULL,
    DATA_ENTREGA DATETIME NULL,
    MINUTOS_GASTOS INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE CONTRATANTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TASK_ID INT NOT NULL,
    INICIO_CONTRATO DATETIME NOT NULL,
    FIM_CONTRATO DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID)
);