CREATE DATABASE SisTasks;
USE SisTasks;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME NVARCHAR(100) NOT NULL,
    PESSOA_FISICA_JURIDICA INT NOT NULL, -- 0 para pessoa física, 1 para pessoa jurídica
    CONTRATADO_CONTRATANTE INT NOT NULL, -- 0 para contratado, 1 para contratante
    CNPJ NVARCHAR(20) NOT NULL UNIQUE,
    NOME_FANTASIA NVARCHAR(100) NOT NULL,
    CPF NVARCHAR(20) NOT NULL UNIQUE,
    TELEFONE NVARCHAR(20) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL
);

CREATE TABLE TASKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TITULO NVARCHAR(200) NOT NULL,
    DESCRICAO NVARCHAR(MAX) NULL,
    DATA_CRIACAO DATETIME NULL,
    DATA_ENTREGA DATETIME NULL,
    STATUS NVARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE CONTRATANTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TASK_ID INT NOT NULL,
    INICIO_CONTRATO DATETIME NOT NULL,
    FIM_CONTRATO DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID)
);